services:
  - type: worker
    name: slot-bot-v2
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20
      - key: TELEGRAM_BOT_TOKEN
        sync: false
