services:
  - type: web
    name: slot-bot-v2
    env: node
    buildCommand: npm install
    startCommand: npm start
    numInstances: 1
    envVars:
      - key: PORT
        value: 3000
      - key: BOT_MODE
        value: webhook
      - key: NODE_VERSION
        value: 20
      - key: LANG
        value: en
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
